# ===============================================
# Deploy Next.js app in standalone mode to Azure
# ===============================================

name: Build and deploy Next.js standalone to Azure Web App - demo-app-host

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ------------------------------
      # Checkout your repo
      # ------------------------------
      - uses: actions/checkout@v4

      # ------------------------------
      # Setup Node.js
      # ------------------------------
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "22.x" # Or your actual version

      # ------------------------------
      # Install deps and build
      # ------------------------------
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # ------------------------------
      # Copy static files into standalone
      # ------------------------------
      - name: Copy static files to standalone output
        run: |
          mkdir -p .next/standalone/.next
          cp -R .next/static .next/standalone/.next/static

      # ------------------------------
      # Zip only the standalone output
      # ------------------------------
      - name: Zip standalone output for deployment
        run: |
          cd .next/standalone
          zip -r ../../release.zip .

      # ------------------------------
      # Deploy to Azure Web App
      # ------------------------------
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "demo-app-host"
          slot-name: "Production"
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A93E062A607D4A4EBD8FE9974628A010 }}
